import type { Metadata } from 'next';
import { Roboto_Condensed } from 'next/font/google';
import './globals.css';
import styles from './page.module.css';
import Navbar from '@/presentation/components/nav-bar/nav-bar';
import { CharactersContextProvider } from '@/presentation/contexts/characters-context/characters.context';
import { Suspense } from 'react';
import Loading from './loading';

const roboto_condensed = Roboto_Condensed({
  subsets: ['latin'],
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto_condensed.className}>
        <main className={styles.main}>
          <CharactersContextProvider>
            <Navbar />
            <Suspense fallback={<Loading />}>{children}</Suspense>
          </CharactersContextProvider>
        </main>
      </body>
    </html>
  );
}
