import type { Metadata } from 'next';
import { Roboto_Condensed } from 'next/font/google';
import './globals.css';
import styles from './page.module.css';
import Navbar from '@/presentation/components/nav-bar/nav-bar';
import { FavCharactersContextProvider } from '@/presentation/contexts/fav-characters-context/fav-characters.context';
import { Suspense } from 'react';
import ProgressBar from '@/presentation/components/ui/progress-bar/progress-bar';

const roboto_condensed = Roboto_Condensed({ subsets: ['latin'], weight: '400',  })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto_condensed.className}>
        <main className={styles.main}>
          <FavCharactersContextProvider>
            <Navbar />
            <div className={styles.content}>
              <Suspense fallback={<ProgressBar />}>
                {children}
              </Suspense>
            </div>
          </FavCharactersContextProvider>
        </main>
      </body>
    </html>
  );
}
