export const ADD_FAV_CHARACTER = 'ADD_FAV_CHARACTER';
export const REMOVE_FAV_CHARACTER = 'REMOVE_FAV_CHARACTER';
export const ADD_SELECTED_CHARACTER = 'ADD_SELECTED_CHARACTER';
export const REMOVE_SELECTED_CHARACTER = 'REMOVE_SELECTED_CHARACTER';
export const ADD_CHARACTERS = 'ADD_CHARACTERS';
